In [79]:
Assignment-4 WEB SCRAPPING WITH SELENIUM AND BEAUTIFUL SOUP

# Importing all necessary imports for Beutiful Soup and Selenium library
import pandas as pd
import time
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException, ElementNotInteractableException
import requests
from selenium.common.exceptions import TimeoutException


import selenium 


import warnings
warnings.filterwarnings('ignore')

In [65]:
#IMPORTING chrome driver exe


driver = webdriver.Chrome("C:\webdriver\chromedriver.exe")

In [8]:
# Loading url to the chrome driver

url = 'https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos'
driver.get(url)

In [9]:
count = 0
#creating list for rank, uploader)name, video name, no of views, date of upload
rank = []
video_names = []
video_uploader_name = []
views = []
upload_dates = []


    #RANK ELEMENT
try:
    rank_obj = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[1]')[:30]
    for i in rank_obj:
        rank.append(i.text)
except NoSuchElementException :
    rank.append('-')
    
    
   #VIDEO NAME ELEMENT
try:
    videoname_obj = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[2]')[:30]
    for i in videoname_obj:
        video_names.append(i.text.split('[')[0][1:-1])
except NoSuchElementException :
    video_names.append('-')
    
    
    
    #UPLOADER_OF_VIDEO
try:
    uploader_obj = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[3]')[:30]
    for i in uploader_obj:
        video_uploader_name.append(i.text)
except NoSuchElementException :
    video_uploader_name.append('-')
    
    

    #VIEWS ON THE VIDEOS
try:
    view_obj = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[4]')[:30]
    for i in view_obj:
        views.append(i.text)
except NoSuchElementException :
    views.append('-')
    
    
    #DATE OF THE VIDEO ELEMENT
try:
    date_obj = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[5]')[:30]
    for i in date_obj:
        upload_dates.append(i.text)
except NoSuchElementException :
    upload_dates.append('-')

In [10]:
# creating a diction of all the columns
dict = {'rank':rank, 'video_name':video_names,'uploader':video_uploader_name,'Views in Billions':views,'upload_date':upload_dates}

In [11]:
# CREATING TABLE / dATA fRAME OF THE DICTIONARY
table = pd.DataFrame(dict)

In [14]:
table

,rank,video_name,uploader,Views in Billions,upload_date
0,1.,Baby Shark Dance,Pinkfong Kids' Songs & Stories,9.04,"June 17, 2016"
1,2.,Despacito,Luis Fonsi,7.46,"January 12, 2017"
2,3.,Johny Johny Yes Papa,LooLoo Kids,5.58,"October 8, 2016"
3,4.,Shape of You,Ed Sheeran,5.40,"January 30, 2017"
4,5.,See You Again,Wiz Khalifa,5.19,"April 6, 2015"
5,6.,Masha and the Bear – Recipe for Disaster,Get Movies,4.45,"January 31, 2012"
6,7.,Bath Song,Cocomelon – Nursery Rhymes,4.37,"May 2, 2018"
7,8.,Learning Colors – Colorful Eggs on a Farm,Miroshka TV,4.31,"February 27, 2018"
8,9.,Uptown Funk,Mark Ronson,4.24,"November 19, 2014"
9,10.,Gangnam Style,Psy,4.13,"July 15, 2012"
10,11.,Phonics Song with Two Words,ChuChu TV,4.02,"March 6, 2014"
11,12.,Sugar,Maroon 5,3.51,"January 14, 2015"
12,13.,Dame Tu Cosita,El Chombo,3.48,"April 5, 2018"
13,14.,Sorry,Justin Bieber,3.45,"October 22, 2015"
14,15.,Roar,Katy Perry,3.39,"September 5, 2013"
15,16.,Counting Stars,OneRepublic,3.35,"May 31, 2013"
16,17.,Thinking Out Loud,Ed Sheeran,3.29,"October 7, 2014"
17,18.,Wheels on the Bus,Cocomelon – Nursery Rhymes,3.18,"May 24, 2018"
18,19.,Dark Horse,Katy Perry,3.11,"February 20, 2014"
19,20.,Faded,Alan Walker,3.10,"December 3, 2015"
20,21.,Shake It Off,Taylor Swift,3.08,"August 18, 2014"
21,22.,Girls Like You,Maroon 5,3.08,"May 31, 2018"
22,23.,Lean On,Major Lazer,3.07,"March 22, 2015"
23,24.,Bailando,Enrique Iglesias,3.07,"April 11, 2014"
24,25.,Let Her Go,Passenger,3.03,"July 25, 2012"
25,26.,Mi Gente,J Balvin,2.95,"June 29, 2017"
26,27.,Perfect,Ed Sheeran,2.90,"November 9, 2017"
27,28.,Axel F,Crazy Frog,2.90,"June 16, 2009"
28,29.,Waka Waka (This Time for Africa),Shakira,2.89,"June 4, 2010"
29,30.,Hello,Adele,2.86,"October 22, 2015"

Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/. You need to find following details: A) Match title (I.e. 1st ODI) B) Series C) Place D) Date E) Time Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [15]:
#giving the  bcci link to the driver to load in the browser
driver.get('https://www.bcci.tv/')

In [16]:
#Finding the object of the international fixture matches from the dropdown element

internation_fixtures_obj = driver.find_element_by_xpath('/html/body/div[3]/div/div[2]/div[2]/nav/ul/li[1]/div[2]/div/ul/li[1]/a')

In [17]:

#link of the dorpdown eleemnt international fixtures.
link = internation_fixtures_obj.get_attribute('href')
link

'https://www.bcci.tv/international/fixtures'

In [18]:
#navigating to the international fixtures link.

driver.get(link)

In [19]:
date = []
time = []
series = []
place = []
match_title = []
match_details = []

# MERging Month and Day together for Date OBject
try :
    month_obj = driver.find_elements_by_xpath('//span[@class="fixture__month"]')
    day_obj = driver.find_elements_by_xpath('//span[@class="fixture__date"]')
    for i in range(len(month_obj)):
        date.append(str(day_obj[i].text)+'-'+str(month_obj[i].text).lower())
except NoSuchElementException:
    date.append('-')
    
    
# Time of match  

try :
    time_obj = driver.find_elements_by_xpath('//span[@class="fixture__time"]')
    
    for i in range(len(time_obj)):
        time.append(str(time_obj[i].text))
except NoSuchElementException:
    time.append('-')

    
#series details and Match Tittle

try :
    series_obj = driver.find_elements_by_xpath('//span[@class="u-unskewed-text fixture__format"]')
    title_obj = driver.find_elements_by_xpath('//span[@class="u-unskewed-text fixture__tournament-label u-truncated"]')
    for i in range(len(month_obj)):
        series.append(str(series_obj[i].text)+' '+str(title_obj[i].text))
        match_title.append(str(title_obj[i].text))
except NoSuchElementException:
    series.append('-')

    
# Location of MAtch, and series information

try :
    location_obj = driver.find_elements_by_xpath('//p[@class="fixture__additional-info"]/span')
    match_name_obj = driver.find_elements_by_xpath('//strong[@class="fixture__name fixture__name--with-margin"]')
    for i in range(len(time_obj)):
        place.append(str(location_obj[i].text))
        match_details.append(match_name_obj[i].text)
except NoSuchElementException:
    place.append ('-')

In [20]:
#creating the dictionary of the elements
dict= {
    'Date':date,'Time':time,'Series':series,'Match': match_title,'Match Location':place,
    'series details': match_details
}

#table creating with creating a DataFrame
table = pd.DataFrame(dict)

In [21]:
table

,Date,Time,Series,Match,Match Location,series details
0,28-july,20:00 IST,T20I SRI LANKA V INDIA 2021,SRI LANKA V INDIA 2021,"R Premadasa Stadium, Colombo",2nd T20I
1,29-july,20:00 IST,T20I SRI LANKA V INDIA 2021,SRI LANKA V INDIA 2021,"R Premadasa Stadium, Colombo",3rd T20I
2,04-august,15:30 IST,TEST ENGLAND V INDIA 2021,ENGLAND V INDIA 2021,"Trent Bridge, Nottingham",1st Test
3,12-august,15:30 IST,TEST ENGLAND V INDIA 2021,ENGLAND V INDIA 2021,"Lord's, London",2nd Test
4,25-august,15:30 IST,TEST ENGLAND V INDIA 2021,ENGLAND V INDIA 2021,"Headingley, Leeds",3rd Test
5,02-september,15:30 IST,TEST ENGLAND V INDIA 2021,ENGLAND V INDIA 2021,"The Oval, London",4th Test
6,10-september,15:30 IST,TEST ENGLAND V INDIA 2021,ENGLAND V INDIA 2021,"Old Trafford, Manchester",5th Test

Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/ You need to find following details: A) Name B) Description Note: - From guru99 home page you have to reach to selenium exception handling page through code

In [22]:
#Loading guru99 in web browser

driver.get('https://www.guru99.com/')

In [23]:
#clicking on Selenium tutorial

driver.find_element_by_xpath("//div[@class='srch']/span[8]/a").click()

In [24]:
# finding the link of Selenium Common Exceptions list and gettting its url and loading it to the web browser

exception_link = driver.find_element_by_xpath("/html/body/div[2]/section[3]/div/div[1]/main/div/div/div/div/div/div/div[2]/table[5]/tbody/tr[34]/td[1]/a")

driver.get(exception_link.get_attribute('href'))

In [25]:
# All datas are available in table format , no missing vlaues to cause exceptions.

row_obj = driver.find_elements_by_xpath('//*[@id="g-mainbar"]/div/div/div/div/div/div/div[2]/table/tbody/tr')

In [26]:
name = []
details = []
for i in row_obj[1:]:
    
    # Splitting the Row as -> each data(each elemeny in loop) contains name and details together.
    
    exception_name = i.text.split(' ')[0]
    
    #Splitting the data with exception name as without exception name , else is details parts.
    
    exception_desc = i.text.split(exception_name)[1]
    name.append(exception_name)
    details.append(exception_desc)
    
#Creating a dataFrame of exceptions name and exception Details.
table = pd.DataFrame({'Exception_Name':name,'Exception_details':details})

In [27]:
table

,Exception_Name,Exception_details
0,ElementNotVisibleException,This type of Selenium exception occurs when a...
1,ElementNotSelectableException,This Selenium exception occurs when an elemen...
2,NoSuchElementException,This Exception occurs if an element could not...
3,NoSuchFrameException,This Exception occurs if the frame target to ...
4,NoAlertPresentException,This Exception occurs when you switch to no p...
5,NoSuchWindowException,This Exception occurs if the window target to...
6,StaleElementReferenceException,This Selenium exception occurs happens when t...
7,SessionNotFoundException,The WebDriver is acting after you quit the br...
8,TimeoutException,Thrown when there is not enough time for a co...
9,WebDriverException,This Exception takes place when the WebDriver...
10,ConnectionClosedException,This type of Exception takes place when there...
11,ElementClickInterceptedException,The command may not be completed as the eleme...
12,ElementNotInteractableException,This Selenium exception is thrown when any el...
13,ErrorInResponseException,This happens while interacting with the Firef...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if...
15,ImeActivationFailedException,This expectation will occur when IME engine a...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certi...
18,InvalidArgumentException,It occurs when an argument does not belong to...
19,InvalidCookieDomainException,This happens when you try to add a cookie und...
20,InvalidCoordinatesException,This type of Exception matches an interacting...
21,InvalidElementStateExceptio,It occurs when command can't be finished when...
22,InvalidSessionIdException,This Exception took place when the given sess...
23,InvalidSwitchToTargetException,This occurs when the frame or window target t...
24,JavascriptException,This issue occurs while executing JavaScript ...
25,JsonException,It occurs when you afford to get the session ...
26,NoSuchAttributeException,This kind of Exception occurs when the attrib...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the ...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching...
30,NotFoundException,This Exception is a subclass of WebDriverExce...
31,RemoteDriverServerException,This Selenium exception is thrown when the se...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be su...
34,UnableToSetCookieException,This occurs if a driver is unable to set a co...
35,UnexpectedTagNameException,Happens if a support class did not get a web ...
36,UnhandledAlertException,This expectation occurs when there is an aler...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an ...
38,UnknownMethodException,This Exception happens when the requested com...
39,UnreachableBrowserException,This Exception occurs only when the browser i...
40,UnsupportedCommandException,This occurs when remote WebDriver does n't se...


Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:
A) Rank
B) State
C) GSDP at current price (19-20)
D) GSDP at current price (18-19)
E) Share(18-19)
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code.

In [28]:
#loading the url in the browser

driver.get('http://statisticstimes.com/')

In [29]:
#finding the link of Economy of INdia 

india_economy_page = driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]')

#extracting the url from the element

link  = india_economy_page.get_attribute('href')

In [30]:
#giving the india economy url to the browser

driver.get(link)

In [31]:
#Click the State-wise gdp of india element

driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/ul/li[1]/a').click()

In [32]:
ranks = []
states = []
GSDP_current_price_19_20 = []
GSDP_current_price_18_19 = []
share_18_19 = []
gdp_19 = []

    #Rank Element

try:
    rank_element = driver.find_elements_by_xpath('/html/body/div[3]/div[2]/div[5]/div[1]/div/table/tbody/tr/td[1]')
    for i in rank_element:
        ranks.append(i.text)
except NoSuchElementException:
    ranks.append('-')
    
    #State Element

try:
    state_element = driver.find_elements_by_xpath('/html/body/div[3]/div[2]/div[5]/div[1]/div/table/tbody/tr/td[2]')
    for i in state_element:
        states.append(i.text)
except NoSuchElementException:
    states.append('-')
   
    
    #GSDP 19-20 element

try:
    GSDP_19_20_element = driver.find_elements_by_xpath('/html/body/div[3]/div[2]/div[5]/div[1]/div/table/tbody/tr/td[3]')
    for i in GSDP_19_20_element:
        GSDP_current_price_19_20.append(i.text)
except NoSuchElementException:
    GSDP_current_price_19_20.append('-')
    
     #GSDP 18-19 element
    
try:
    GSDP_18_19_element = driver.find_elements_by_xpath('/html/body/div[3]/div[2]/div[5]/div[1]/div/table/tbody/tr/td[4]')
    for i in GSDP_18_19_element:
        GSDP_current_price_18_19.append(i.text)
except NoSuchElementException:
    GSDP_current_price_18_19.append('-')
    
    
    #share element for 18-19
    
try:
    share_element = driver.find_elements_by_xpath('/html/body/div[3]/div[2]/div[5]/div[1]/div/table/tbody/tr/td[5]')
    for i in share_element:
        share_18_19.append(i.text)
except NoSuchElementException:
    share_18_19.append('-')
    
    
    #GDP of 2019
    
try:
    GDP_element = driver.find_elements_by_xpath('/html/body/div[3]/div[2]/div[5]/div[1]/div/table/tbody/tr/td[6]')
    for i in GDP_element:
        gdp_19.append(i.text)
except NoSuchElementException:
    gdp_19.append('-')

In [33]:
#Creating a Dictionarty of the all the elements

dict = {
    'RANK':ranks, 'STATE':states,'GSDP_19_20': GSDP_current_price_19_20,'GSDP_18_19':GSDP_current_price_18_19,
    'SHARE_PRICE_2019':share_18_19,'GDP_in_billions':gdp_19
    }

#loading the dictionary to a dataframe 
table = pd.DataFrame(dict)
table

,RANK,STATE,GSDP_19_20,GSDP_18_19,SHARE_PRICE_2019,GDP_in_billions
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used

In [34]:
#loading github.com url to the browser

driver.get('https://github.com/')

In [35]:
#find the element of the Trending from the dropdown of the EXPLORE column and extracting the URL of trending

link_trending = driver.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul[2]/li[3]/a').get_attribute('href')
link_trending

'https://github.com/trending'

In [36]:
#feeding the trending url to the browser

driver.get(link_trending)

In [37]:
repo_titles = []

repo_urls = []

#Extraction Repository Name and its corresponding urls
title_element = driver.find_elements_by_xpath('//*[@id="js-pjax-container"]/div[3]/div/div[2]/article/h1/a')
for i in title_element:
    repo_urls.append(i.get_attribute('href'))
    repo_titles.append(i.text)

In [39]:
#ALL REPOSiTORY URLS
repo_urls

['https://github.com/mvt-project/mvt',
 'https://github.com/Megvii-BaseDetection/YOLOX',
 'https://github.com/AmnestyTech/investigations',
 'https://github.com/flutter/flutter',
 'https://github.com/doocs/source-code-hunter',
 'https://github.com/public-apis/public-apis',
 'https://github.com/jwasham/coding-interview-university',
 'https://github.com/microsoft/CBL-Mariner',
 'https://github.com/nocodb/nocodb',
 'https://github.com/tinode/chat',
 'https://github.com/blueedgetechno/windows11',
 'https://github.com/CryptoBlades/cryptoblades',
 'https://github.com/ventoy/Ventoy',
 'https://github.com/topotam/PetitPotam',
 'https://github.com/forem/selfhost',
 'https://github.com/LaravelDaily/Laravel-Roadmap-Learning-Path',
 'https://github.com/trekhleb/learn-python',
 'https://github.com/verymeticulous/wikAPEdia',
 'https://github.com/loong132/autojs-script',
 'https://github.com/Xmader/musescore-downloader',
 'https://github.com/JuliaLang/julia',
 'https://github.com/zhenghaoz/gorse',
 'https://github.com/capt-meelo/Beaconator',
 'https://github.com/Universidade-Livre/ciencia-da-computacao',
 'https://github.com/protocolbuffers/protobuf']

In [42]:
repo_descriptions = []
contributors_counts = []
language_used  = []

#LOOPING THROUGH THE REPOSITORY URLS TO EXTRACT DATA FROM EACH LINK>

for  i in repo_urls:
    
    #loading the repositroy link to the browsetr
    driver.get(i)
    #waitng for the browser to load and keep the browser to sleep mode for 2 sec
    
    
    
    #DESCRIPTION OF REPOSITORY
    try :
        description_element = driver.find_element_by_xpath('//*[@id="repo-content-pjax-container"]/div/div[2]/div[2]/div/div[1]/div/p')
        
        repo_descriptions.append(description_element.text)
    except NoSuchElementException:
        repo_descriptions.append('-')

    #CONTRIBUTORS_cOUNT
    try :
        contributors_element = driver.find_element_by_xpath('/html/body/div[4]/div/main/div[2]/div/div/div[2]/div[2]/div/div[5]/div/h2/a/span')
       
        contributors_counts.append(contributors_element.text)
    except NoSuchElementException:
        contributors_counts.append('-')

    #LANGUAGES used

    try :
        language_element = driver.find_elements_by_xpath('//*[@id="repo-content-pjax-container"]/div/div[2]/div[2]/div/div[1]/div/div[1]/div/a')
        li = []
        for i in language_element:
           
            li.append(i.text)
        language_used.append(', '.join(li))
    except NoSuchElementException:
        language_used.append('-')

In [43]:
#creating a dictionary of all the elements
dict={
    'Repository_title': repo_titles,
    'Repo_description':repo_descriptions,
    'Contributors': contributors_counts,
    'Languages Used': language_used,
    
}

#table creation with DATAFRAME
table = pd.DataFrame(dict)

In [45]:
#table creation with DATAFRAME
table = pd.DataFrame(dict)
table

,Repository_title,Repo_description,Contributors,Languages Used
0,mvt-project / mvt,MVT is a forensic tool to look for signs of in...,-,
1,Megvii-BaseDetection / YOLOX,"YOLOX is a high-performance anchor-free YOLO, ...",11,"pytorch, object-detection, tensorrt, ncnn, onn..."
2,AmnestyTech / investigations,Indicators from Amnesty International's invest...,4,
3,flutter / flutter,Flutter makes it easy and fast to build beauti...,-,
4,doocs / source-code-hunter,😱 从源码层面，剖析挖掘互联网行业主流技术的底层实现原理，为广大开发者 “提升技术深度” 提...,-,
5,public-apis / public-apis,A collective list of free APIs,-,"api, list, development, public, free, software..."
6,jwasham / coding-interview-university,A complete computer science study plan to beco...,205,"computer-science, algorithm, algorithms, inter..."
7,microsoft / CBL-Mariner,Linux OS for Azure 1P services and edge applia...,37,
8,nocodb / nocodb,🔥 🔥 The Open Source Airtable alternative - Pow...,33,
9,tinode / chat,Instant messaging platform. Backend in Go. Cli...,26,"go, chat, golang, telegram, messaging, xmpp, m..."
10,blueedgetechno / windows11,windows 11 in react 💻🌈⚡,-,
11,CryptoBlades / cryptoblades,-,-,
12,ventoy / Ventoy,A new bootable USB solution.,-,
13,topotam / PetitPotam,-,4,
14,forem / selfhost,Selfhost your Forem Community on your own infr...,-,
15,LaravelDaily / Laravel-Roadmap-Learning-Path,-,2,
16,trekhleb / learn-python,📚 Playground and cheatsheet for learning Pytho...,10,"python, programming-language, learning, learni..."
17,verymeticulous / wikAPEdia,A central place for apes to learn about stonks...,-,
18,loong132 / autojs-script,"autojs脚本程序,用于完成安卓设备上的重复性操作.包含脚本: 1.2021年京东618任...",-,
19,Xmader / musescore-downloader,"Download sheet music (MSCZ, PDF, MusicXML, MID...",11,
20,JuliaLang / julia,The Julia Programming Language,"1,170",
21,zhenghaoz / gorse,An open source recommender system service writ...,14,
22,capt-meelo / Beaconator,A beacon generator using Cobalt Strike and PEzor.,-,
23,Universidade-Livre / ciencia-da-computacao,🎓 Um caminho para a educação autodidata em Ciê...,-,"computer-science, awesome-list, brasil, cursos..."
24,protocolbuffers / protobuf,Protocol Buffers - Google's data interchange f...,764,

In [46]:
#creating a dictionary of all the elements
dict={
    'Repository_title': repo_titles,
    'Repo_description':repo_descriptions,
    'Contributors': contributors_counts,
    'Languages Used': language_used,
    
}

#table creation with DATAFRAME
table = pd.DataFrame(dict)
table

,Repository_title,Repo_description,Contributors,Languages Used
0,mvt-project / mvt,MVT is a forensic tool to look for signs of in...,-,
1,Megvii-BaseDetection / YOLOX,"YOLOX is a high-performance anchor-free YOLO, ...",11,"pytorch, object-detection, tensorrt, ncnn, onn..."
2,AmnestyTech / investigations,Indicators from Amnesty International's invest...,4,
3,flutter / flutter,Flutter makes it easy and fast to build beauti...,-,
4,doocs / source-code-hunter,😱 从源码层面，剖析挖掘互联网行业主流技术的底层实现原理，为广大开发者 “提升技术深度” 提...,-,
5,public-apis / public-apis,A collective list of free APIs,-,"api, list, development, public, free, software..."
6,jwasham / coding-interview-university,A complete computer science study plan to beco...,205,"computer-science, algorithm, algorithms, inter..."
7,microsoft / CBL-Mariner,Linux OS for Azure 1P services and edge applia...,37,
8,nocodb / nocodb,🔥 🔥 The Open Source Airtable alternative - Pow...,33,
9,tinode / chat,Instant messaging platform. Backend in Go. Cli...,26,"go, chat, golang, telegram, messaging, xmpp, m..."
10,blueedgetechno / windows11,windows 11 in react 💻🌈⚡,-,
11,CryptoBlades / cryptoblades,-,-,
12,ventoy / Ventoy,A new bootable USB solution.,-,
13,topotam / PetitPotam,-,4,
14,forem / selfhost,Selfhost your Forem Community on your own infr...,-,
15,LaravelDaily / Laravel-Roadmap-Learning-Path,-,2,
16,trekhleb / learn-python,📚 Playground and cheatsheet for learning Pytho...,10,"python, programming-language, learning, learni..."
17,verymeticulous / wikAPEdia,A central place for apes to learn about stonks...,-,
18,loong132 / autojs-script,"autojs脚本程序,用于完成安卓设备上的重复性操作.包含脚本: 1.2021年京东618任...",-,
19,Xmader / musescore-downloader,"Download sheet music (MSCZ, PDF, MusicXML, MID...",11,
20,JuliaLang / julia,The Julia Programming Language,"1,170",
21,zhenghaoz / gorse,An open source recommender system service writ...,14,
22,capt-meelo / Beaconator,A beacon generator using Cobalt Strike and PEzor.,-,
23,Universidade-Livre / ciencia-da-computacao,🎓 Um caminho para a educação autodidata em Ciê...,-,"computer-science, awesome-list, brasil, cursos..."
24,protocolbuffers / protobuf,Protocol Buffers - Google's data interchange f...,764,

In [47]:
table

,Repository_title,Repo_description,Contributors,Languages Used
0,mvt-project / mvt,MVT is a forensic tool to look for signs of in...,-,
1,Megvii-BaseDetection / YOLOX,"YOLOX is a high-performance anchor-free YOLO, ...",11,"pytorch, object-detection, tensorrt, ncnn, onn..."
2,AmnestyTech / investigations,Indicators from Amnesty International's invest...,4,
3,flutter / flutter,Flutter makes it easy and fast to build beauti...,-,
4,doocs / source-code-hunter,😱 从源码层面，剖析挖掘互联网行业主流技术的底层实现原理，为广大开发者 “提升技术深度” 提...,-,
5,public-apis / public-apis,A collective list of free APIs,-,"api, list, development, public, free, software..."
6,jwasham / coding-interview-university,A complete computer science study plan to beco...,205,"computer-science, algorithm, algorithms, inter..."
7,microsoft / CBL-Mariner,Linux OS for Azure 1P services and edge applia...,37,
8,nocodb / nocodb,🔥 🔥 The Open Source Airtable alternative - Pow...,33,
9,tinode / chat,Instant messaging platform. Backend in Go. Cli...,26,"go, chat, golang, telegram, messaging, xmpp, m..."
10,blueedgetechno / windows11,windows 11 in react 💻🌈⚡,-,
11,CryptoBlades / cryptoblades,-,-,
12,ventoy / Ventoy,A new bootable USB solution.,-,
13,topotam / PetitPotam,-,4,
14,forem / selfhost,Selfhost your Forem Community on your own infr...,-,
15,LaravelDaily / Laravel-Roadmap-Learning-Path,-,2,
16,trekhleb / learn-python,📚 Playground and cheatsheet for learning Pytho...,10,"python, programming-language, learning, learni..."
17,verymeticulous / wikAPEdia,A central place for apes to learn about stonks...,-,
18,loong132 / autojs-script,"autojs脚本程序,用于完成安卓设备上的重复性操作.包含脚本: 1.2021年京东618任...",-,
19,Xmader / musescore-downloader,"Download sheet music (MSCZ, PDF, MusicXML, MID...",11,
20,JuliaLang / julia,The Julia Programming Language,"1,170",
21,zhenghaoz / gorse,An open source recommender system service writ...,14,
22,capt-meelo / Beaconator,A beacon generator using Cobalt Strike and PEzor.,-,
23,Universidade-Livre / ciencia-da-computacao,🎓 Um caminho para a educação autodidata em Ciê...,-,"computer-science, awesome-list, brasil, cursos..."
24,protocolbuffers / protobuf,Protocol Buffers - Google's data interchange f...,764,

Scrape the details of top 100 songs on billboard.com.
Url = https://www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board


Note: - From the home page you have to click on the charts option then hot 100-page link through code

In [60]:
driver.get('https://www.billboard.com/')

In [61]:
#Finding full Xpath of the Hot 100 -> from Charts

link = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/header/div/ul/li[1]/span/span/span/span[1]/ul/li[1]/a').get_attribute('href')
link

'https://www.billboard.com/charts/hot-100'

In [62]:
#loading the extracted link of the hot top 100
driver.get(link)

In [ ]:
song = []
artist = []
last_week_rank = []
peak_rank = []
weeks_on_board = []

#SONG NAME ELEMENT EXTRACTION
try:
    song_name_obj = driver.find_elements_by_xpath('//span[@class="chart-element__information"]/span[1]')
   
    for i in range(len(song_name_obj)):
        song.append(song_name_obj[i].text)
except NoSuchElementException:
    song.append('-')
    
    
#ARTIST NAME ELEMENT EXTRACTION
try:
   
    singer_name_obj = driver.find_elements_by_xpath('//span[@class="chart-element__information"]/span[2]')
    for i in range(len(singer_name_obj)):
        
        artist.append(singer_name_obj[i].text)
except NoSuchElementException:
    artist.append('-')
    
    
#LAST WEEK RANK of a SONG  ELEMENT EXTRACTION    
    #chart-element__metas chart-element__metas--large display--flex flex--y-center
try:
    rank_lastweek_obj = driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--last"]')
   
    for i in range(len(rank_lastweek_obj)):
        last_week_rank.append(rank_lastweek_obj[i].text)
except NoSuchElementException:
    last_week_rank.append('-')
    
    
#PEAK RANK OF A SONG ELEMENT EXTRACTION    
try:
   
    peak_rank_obj = driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--peak"]')
    for i in range(len(peak_rank_obj)):
        
        peak_rank.append(peak_rank_obj[i].text)
except NoSuchElementException:
     peak_rank.append('-')  
        
        
#WEEKS ON BOARD for a SONG ELEMENT EXTRACTION
try:
   
    no_of_weeks_onboard_obj = driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--week"]')
    for i in range(len(no_of_weeks_onboard_obj)):
        
        weeks_on_board.append(no_of_weeks_onboard_obj[i].text)
except NoSuchElementException:
    weeks_on_board.append('-')

In [68]:
dict = {
    'song_name': song, 'artist_name':artist,
    'last_week_rank': last_week_rank,'peak_rank':peak_rank,'no_of_weeks_onboard': weeks_on_board
}
table = pd.DataFrame(dict)
table
table

Empty DataFrame
Columns: [song_name, artist_name, last_week_rank, peak_rank, no_of_weeks_onboard]
Index: []

Scrape the details of Data science recruiters from naukri.com. Url = https://www.naukri.com/

Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/
You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
click on search. A

In [66]:
#loading the naukri .com url to the website.
driver.get('https://naukri.com')

In [69]:
#recruitor page link element
recruiter_link = driver.find_element_by_xpath('/html/body/div[1]/div[1]/div/ul[1]/li[2]/a').get_attribute('href')

In [70]:
#loading the recruitor link to the browser
driver.get(recruiter_link)

In [71]:
driver.current_url

'https://www.naukri.com/hr-recruiters-consultants'

In [72]:
#element of Search tab and seARCH button
input_tab = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/div/div[1]/div[1]/div[2]/input')
search_btn = driver.find_element_by_xpath('//button[@class="fl qsbSrch blueBtn"]')

In [73]:
#sending keys to the Search Tab
input_tab.send_keys('Data Science')

In [74]:
#click the  search element
search_btn.click()

In [75]:
#extracting the link elements of the recruitors
recruiter_name = driver.find_elements_by_xpath("//p[@class='highlightable']/a[1]")

In [76]:
#Links of all the companies
all_recruitment_links = []
for i in recruiter_name:
    all_recruitment_links.append(i.get_attribute('href'))

In [80]:
re_names= []
re_company = []
re_location = []
re_skills = []
re_designation = []
#lopping through each company to extract data of each company seperately.
for i in range(50):
    driver.get(all_recruitment_links[i])
   
    
    #Recruiter Name
    try:
        name_element = driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[1]/div[2]/div[2]/h1')
        re_names.append(name_element.text)
    except NoSuchElementException:
        re_names.append('-')
        
    #Company NAme
    try:
        company_element = driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[2]/div[2]/div[2]/p[1]')
        re_company.append(company_element.text)
    except NoSuchElementException:
        re_company.append('-')
    
    #Location element
    try:
        location_element = driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[1]/div[2]/div[5]/a')
       # for i in location_element:
        re_location.append(location_element.text)
    except NoSuchElementException:
        re_location.append('-')
        
    #Skills
    try:
        skills_element = driver.find_elements_by_xpath('/html/body/div[2]/div[1]/div[2]/div[2]/div[1]/p')
        li = []
        for i in skills_element:
            li.append(i.text)
            
        temp = ' '.join(li) 
        re_skills.append(temp)
        
    except NoSuchElementException:
        re_skills.append('-')
      
    
    #Designation element
    try:
        designation_element = driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[1]/div[2]/div[3]')
        re_designation.append(designation_element.text)
    except NoSuchElementException:
        re_designation.append('-')

In [81]:
#creating a dictionary of all the elements
dict = {
    'Recruiter_Name': re_names,'Recruiter_Company':re_company,
    'Recruiter_Designation':re_designation,'Skills_needed':re_skills,
    'Location':re_location
}
#creating a DataFrame/ Table of the dictionary
table = pd.DataFrame(dict)
table

,Recruiter_Name,Recruiter_Company,Recruiter_Designation,Skills_needed,Location
0,Aakash Harit,Data Science Network,HR Manager,"Classic ASP Developer , Internet Marketing Pro...",Delhi
1,shravan Kumar Gaddam,Shore Infotech India Pvt. Ltd (Since Dec-2016),Company Recruiter,".Net , Java , Data Science , Linux Administrat...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,MARSIAN Technologies LLP (Since Feb-2016),Company HR,"Mid Level, Junior Level",Pune
3,Anik Agrawal,Enerlytics Software Solutions Pvt Ltd,Company Recruiter,", Mean Stack , javascript , angularjs , mongod...",Ahmedabad
4,subhas patel,LibraryXProject,Founder & CEO,"Hadoop , Spark , Digital Strategy , Data Archi...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and APAC,Apidel Technologies Division of Transpower (Si...,Recruitment - Lead Consultant,"Analytics , Business Intelligence , Business A...",Vadodara / Baroda
6,Institute for Financial Management and Research,IFMR (Since May-2017),Programme Manager,Analytics & Business Intelligence,Chennai
7,Balu Ramesh,Techvantage Systems Pvt Ltd (Since Dec-2014),HR Administrator,"Machine Learning , algorithms , Go Getter , Co...",Trivandrum
8,Asif Lucknowi,-,Director,Weupskill- Live Wire India,Indore
9,InstaFinancials,CBL Data Science Private Limited,Human Resource,"Junior Level, Mid Level",Bengaluru / Bangalore
10,Kalpana Dumpala,Innominds Software (Since Feb-2015),Executive Hiring,"Qa , Ui , ux , Java Developer , Java Architect...",Hyderabad / Secunderabad
11,Mubarak,-,Company HR,MoneyTap,Bengaluru / Bangalore
12,Kushal Rastogi,-,Company HR,QuantMagnum Technologies Pvt. Ltd.,Mumbai
13,Ruchi Dhote,Bristlecone India Ltd (Since Apr-2021),Senior Executive Talent Acquisition,IT Skills,Pune
14,Mahesh Babu Channa,SocialPrachar.com (Since Jan-2014),HR Team Lead,"Junior Level, Mid Level",Hyderabad / Secunderabad
15,Kapil Devang,BISP Solutions,HR Manager,"Big Data , Hadoop , Data Analytics , Data Science",Bhopal
16,Manisha Yadav,Easi Tax,HR Executive,Mid Level,Navi Mumbai
17,Riya Rajesh,Novelworx Digital Solutions (Since May-2019),Manager Talent Acquisition,IT-Software/Software Services,Cochin
18,Rashmi Bhattacharjee,AXESTRACK SOFTWARE SOLUTIONS PRIVATE LIMITED,HR Head,"Mid Level, Top Mangement Level",Delhi
19,Faizan Kareem,FirstTech Consaltants Pvt.Ltd,HR MANAGER,"Data Analytics , Data Science , Machine Learni...",Hyderabad / Secunderabad
20,Rithika dadwal,Affine Analytics,HR Recruiter,"Junior Level, Mid Level",Pune
21,Azahar Shaikh,NEAL ANALYTICS SERVICES PVT LTD,Company Recruiter,"Mid Level, High Level",Pune
22,Sandhya Khandagale,Compumatrice Multimedia Pvt Ltd,HR Recruiter,"High Level, Mid Level",Pune
23,Shaun Rao,Exela Technologies (Since Nov-2014),Manager - Human Resources,"Java , Net , Angularjs , Hr , Infrastructure ,...",Pune
24,Manas,Autumn Leaf Consulting Services Private Limited,Lead Talent acquisition,"High Level, Top Mangement Level",Bengaluru / Bangalore
25,kumar,trainin,Proprietor,"Data Science , Hadoop , Rpas , Devops , Python...",Bengaluru / Bangalore
26,Sunil Vedula,Nanoprecise Sci Corp,CEO,"Signal Processing , Machine Learning , Neural ...",Others
27,Rajat Kumar,R.S Consultancy & Services,Founder & CEO,"Web Technologies , Project Management , Softwa...",Delhi
28,Priya Khare,-,Senior Manager,Independent Consultant,Bengaluru / Bangalore
29,Dhruv Dev Dubey,Confidential (Since Jun-2016),Company Recruitment Head,"S. Finance Manager , Freshers , Experience , S...",Bengaluru / Bangalore
30,Jayanth N,"Dollarbird Information Services Pvt, Ltd (Sinc...",Project Manager,"Data Analytics , Managed Services , Team Leading",Mysoru / Mysore
31,SREEDHAR,-,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,Hyderabad / Secunderabad
32,Radha Manivasagam,Techcovery,HR Executive,Junior Level,Bengaluru / Bangalore
33,Ravi Dubey,HyrEzy Talent Solutions LLP,Recruitment Manager,"Mid Level, Top Mangement Level",Ghaziabad
34,Prateek Kumar,Trisect (Since Jan-2013),Head,Junior Level,Noida
35,Amit Sharma,-,Consultant,ASCO consulting,New Delhi
36,Kanan,NY INST,senior technology instructor,"Mid Level, Junior Level",Chennai
37,Shashikant Chaudhary,-,HR Recruiter/HR Excutive,3D India Staffing Research & Consulting Co. In...,Aligarh
38,Brad,O.C. Tanner (Since Jan-2019),"Manager, Technical Recruiting","Junior Level, High Level",Salt Lake City
39,Rutuja Pawar,Demand Matrix (Since Feb-2018),Technical Recruiter,"Python , Php , Qa Automation , Ui , Wordpre",Pune
40,Madhusudhan Sridhar,-,Erp Implementer,MADHUSUDHAN SRIDHAR,Bengaluru / Bangalore
41,Ankit Sinha,-,Head-Analytics,Suntech Global (Since Feb-2018),Mumbai
42,Gaurav Chouhan,Strategic Consulting Lab,Chief Technical Officer,"Top Mangement Level, Junior Level",Indore
43,Rashi Kacker,Impel Labs Pvt. Ltd.,Sr Product Manager,"Data Science , Node.js , Angularjs",Bengaluru / Bangalore
44,Ashwini,-,"Director, Global Delivery",MRP Advisers (Since Oct-2017),MYSORE
45,Balaji Kolli,-,Co-Founder,Saras Solutions India Pvt Ltd,Hyderabad / Secunderabad
46,Rajani Nagaraj,WildJasmine,HR Manager,"java , hadoop , r , Machine Learning , spark ,...",Bengaluru / Bangalore
47,ROHIT Kumar,LNT Private Limited (Since Jul-2017),Architect,"Mid Level, High Level",Mumbai
48,Amir Chowdhury,-,Managing Partner,Granular.ai,
49,Shailja Mishra,-,HR Manager,Certybox Pvt.Ltd.,Noida

Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [82]:
#loading the url to the browser.
driver.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare')

In [83]:
#creating empty list for all the elements
book_names = []
author_names = []
volumes_sold = []
publisher = []
genre = []

In [91]:
#No need for exception handlnig as the data is in table format and all the data points are available to extract.

    #NAME OF BOOK
    Names_obj = driver.find_elements_by_xpath('//*[@id="article-body-blocks"]/div/table/tbody/tr/td[2]')
    for i in name_obj:
        book_names.append(i.text)

    #AUTHOR NAME
    author_obj = driver.find_elements_by_xpath('//*[@id="article-body-blocks"]/div/table/tbody/tr/td[3]')
    for i in author_obj:
        author_names.append(i.text)

        
    #VOLUME OF BOOKS SOLD
    volume_obj = driver.find_elements_by_xpath('//*[@id="article-body-blocks"]/div/table/tbody/tr/td[4]')
    for i in volume_obj:
        volumes_sold.append(i.text)

    #PUBLISHER NAME
    publisher_obj = driver.find_elements_by_xpath('//*[@id="article-body-blocks"]/div/table/tbody/tr/td[5]')
    for i in publisher_obj:
        publisher.append(i.text)

        
    #GENRE ELEMENT
    genre_obj = driver.find_elements_by_xpath('//*[@id="article-body-blocks"]/div/table/tbody/tr/td[6]')
    for i in genre_obj:
        genre.append(i.text)

IndentationError: unexpected indent (<ipython-input-91-a6afe88dc2dd>, line 4)

In [92]:
#Creating a dictionary of all the elements
dict = {
    'BOOK_NAME':book_names,'AUTHOR_NAME':author_names,'VOLUME_SOLD':volumes_sold,
    'PUBLISHER_NAME':publisher,'GENRE':genre
}
#Dataframe/Table creating of the dictionary
table = pd.DataFrame(dict)

In [93]:
table

Empty DataFrame
Columns: [BOOK_NAME, AUTHOR_NAME, VOLUME_SOLD, PUBLISHER_NAME, GENRE]
Index: []

In [95]:
#No need for exception handlnig as the data is in table format and all the data points are available to extract.

    #NAME OF BOOK
    name_obj = driver.find_elements_by_xpath('//*[@id="article-body-blocks"]/div/table/tbody/tr/td[2]')
    for i in name_obj:
        book_names.append(i.text)

    #AUTHOR NAME
    author_obj = driver.find_elements_by_xpath('//*[@id="article-body-blocks"]/div/table/tbody/tr/td[3]')
    for i in author_obj:
        author_names.append(i.text)

        
    #VOLUME OF BOOKS SOLD
    volume_obj = driver.find_elements_by_xpath('//*[@id="article-body-blocks"]/div/table/tbody/tr/td[4]')
    for i in volume_obj:
        volumes_sold.append(i.text)

    #PUBLISHER NAME
    publisher_obj = driver.find_elements_by_xpath('//*[@id="article-body-blocks"]/div/table/tbody/tr/td[5]')
    for i in publisher_obj:
        publisher.append(i.text)

        
    #GENRE ELEMENT
    genre_obj = driver.find_elements_by_xpath('//*[@id="article-body-blocks"]/div/table/tbody/tr/td[6]')
    for i in genre_obj:
        genre.append(i.text)

IndentationError: unexpected indent (<ipython-input-95-81da984cc921>, line 4)

In [96]:

#Creating a dictionary of all the elements
dict = {
    'BOOK_NAME':book_names,'AUTHOR_NAME':author_names,'VOLUME_SOLD':volumes_sold,
    'PUBLISHER_NAME':publisher,'GENRE':genre
}
#Dataframe/Table creating of the dictionary
table = pd.DataFrame(dict)
table

Empty DataFrame
Columns: [BOOK_NAME, AUTHOR_NAME, VOLUME_SOLD, PUBLISHER_NAME, GENRE]
Index: []

Scrape the details most watched tv series of all time from imdb.com.
    Url = https://www.imdb.com/list/ls095964455/
    You have to find the following details:
    A) Name
    B) Year span
    C) Genre
    D) Run time
    E) Ratings
    F) Votes

In [97]:
#Laoding the url to the browser
driver.get('https://www.imdb.com/list/ls095964455/')

In [98]:
movies = []
year_span = []
genre = []
run_time = []
ratings = []
votes = []

In [99]:
#AS all elements are avaialbe, no exception needed

In [100]:
#MOIVE NAME ELEMENT

movie_name_obj = driver.find_elements_by_xpath('//h3[@class="lister-item-header"]/a')
for i in movie_name_obj:
    movies.append(i.text)

        
    #YEAR SPAN OBJECT

year_span_obj = driver.find_elements_by_xpath('//h3[@class="lister-item-header"]/span[2]')
for i in year_span_obj:
    year_span.append(i.text)

    #GENRE OBJECT

genre_obj = driver.find_elements_by_xpath('//span[@class="genre"]')
for i in genre_obj:
    genre.append(i.text)

        
    #RUNTIME ELEMENT
    
runtime_obj = driver.find_elements_by_xpath('//span[@class="runtime"]')
for i in runtime_obj:
    run_time.append(i.text)

    #RATING OBJECT
    
rating_obj = driver.find_elements_by_xpath('//div[@class="ipl-rating-star small"]/span[2]')
for i in rating_obj:
    ratings.append(i.text)

    #NO OF VOTES OBJECT
       
votes_obj = driver.find_elements_by_xpath('//*[@id="main"]/div/div[3]/div[3]/div/div[2]/p[4]/span[2]')
for i in votes_obj:
    votes.append(i.text)

In [101]:
#creating a dictionary of all the elements
dict = {
    'movie':movies,'duration time':run_time,'Genre':genre,
    'Rating':ratings,'Votes':votes,'Year_span':year_span
}
#data frame creation
table = pd.DataFrame(dict)
table

,movie,duration time,Genre,Rating,Votes,Year_span
0,Game of Thrones,57 min,"Action, Adventure, Drama",9.2,"1,843,565",(2011–2019)
1,Stranger Things,51 min,"Drama, Fantasy, Horror",8.7,"881,887",(2016– )
2,The Walking Dead,44 min,"Drama, Horror, Thriller",8.2,"883,423",(2010–2022)
3,13 Reasons Why,60 min,"Drama, Mystery, Thriller",7.6,"265,215",(2017–2020)
4,The 100,43 min,"Drama, Mystery, Sci-Fi",7.6,"226,478",(2014–2020)
...,...,...,...,...,...,...
95,Reign,42 min,"Drama, Fantasy",7.5,"44,922",(2013–2017)
96,A Series of Unfortunate Events,50 min,"Adventure, Comedy, Drama",7.8,"55,605",(2017–2019)
97,Criminal Minds,42 min,"Crime, Drama, Mystery",8,"171,079",(2005–2020)
98,Scream: The TV Series,45 min,"Comedy, Crime, Drama",7.1,"35,387",(2015–2019)
99,The Haunting of Hill House,572 min,"Drama, Horror, Mystery",8.6,"194,444",(2018)

Details of Datasets from UCI machine learning repositories.
 Url = https://archive.ics.uci.edu/
 You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year

In [102]:
#Loading the url to the browser
driver.get('https://archive.ics.uci.edu/')

In [103]:
#repository element element object
repository_links = driver.find_elements_by_xpath('//span[@class="normal"]/a')

In [104]:
#al lthe repository element links
for i in repository_links:
    print(i.get_attribute('href'))

https://archive.ics.uci.edu/ml/index.html
http://cml.ics.uci.edu/
https://archive.ics.uci.edu/ml/about.html
https://archive.ics.uci.edu/ml/citation_policy.html
https://archive.ics.uci.edu/ml/donation_policy.html
https://archive.ics.uci.edu/ml/contact.html
http://archive.ics.uci.edu/ml/noteNetflix.txt
https://archive.ics.uci.edu/ml/datasets/Communities+and+Crime
https://archive.ics.uci.edu/ml/datasets/Synchronous+Machine+Data+Set
https://archive.ics.uci.edu/ml/datasets/Wikipedia+Math+Essentials
https://archive.ics.uci.edu/ml/datasets/Wikipedia+Math+Essentials
https://archive.ics.uci.edu/ml/datasets/Hungarian+Chickenpox+Cases
https://archive.ics.uci.edu/ml/datasets/Myocardial+infarction+complications
https://archive.ics.uci.edu/ml/datasets/Gait+Classification
https://archive.ics.uci.edu/ml/datasets/Codon+usage
https://archive.ics.uci.edu/ml/datasets/in-vehicle+coupon+recommendation
https://archive.ics.uci.edu/ml/datasets/Dry+Bean+Dataset
https://archive.ics.uci.edu/ml/datasets/Intelligent+Media+Accelerometer+and+Gyroscope+%28IM-AccGyro%29+Dataset
https://archive.ics.uci.edu/ml/datasets/AI4I+2020+Predictive+Maintenance+Dataset
https://archive.ics.uci.edu/ml/datasets/Wisesight+Sentiment+Corpus
https://archive.ics.uci.edu/ml/datasets/Iris
https://archive.ics.uci.edu/ml/datasets/Adult
https://archive.ics.uci.edu/ml/datasets/Wine
https://archive.ics.uci.edu/ml/datasets/Wine+Quality
https://archive.ics.uci.edu/ml/datasets/Heart+Disease
https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+%28Diagnostic%29
https://archive.ics.uci.edu/ml/datasets/Bank+Marketing
https://archive.ics.uci.edu/ml/datasets/Car+Evaluation
https://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones
https://archive.ics.uci.edu/ml/datasets/Abalone
https://archive.ics.uci.edu/ml/datasets/Forest+Fires
https://archive.ics.uci.edu/ml/datasets/Student+Performance
https://archive.ics.uci.edu/ml/about.html
https://archive.ics.uci.edu/ml/citation_policy.html
https://archive.ics.uci.edu/ml/donation_policy.html
https://archive.ics.uci.edu/ml/contact.html
http://cml.ics.uci.edu/

In [105]:
#Dataset URLS
urls = []
for i in repository_links:
    if(i.get_attribute('href').find('datasets')>0):
        urls.append(i.get_attribute('href'))

In [106]:
urls

['https://archive.ics.uci.edu/ml/datasets/Communities+and+Crime',
 'https://archive.ics.uci.edu/ml/datasets/Synchronous+Machine+Data+Set',
 'https://archive.ics.uci.edu/ml/datasets/Wikipedia+Math+Essentials',
 'https://archive.ics.uci.edu/ml/datasets/Wikipedia+Math+Essentials',
 'https://archive.ics.uci.edu/ml/datasets/Hungarian+Chickenpox+Cases',
 'https://archive.ics.uci.edu/ml/datasets/Myocardial+infarction+complications',
 'https://archive.ics.uci.edu/ml/datasets/Gait+Classification',
 'https://archive.ics.uci.edu/ml/datasets/Codon+usage',
 'https://archive.ics.uci.edu/ml/datasets/in-vehicle+coupon+recommendation',
 'https://archive.ics.uci.edu/ml/datasets/Dry+Bean+Dataset',
 'https://archive.ics.uci.edu/ml/datasets/Intelligent+Media+Accelerometer+and+Gyroscope+%28IM-AccGyro%29+Dataset',
 'https://archive.ics.uci.edu/ml/datasets/AI4I+2020+Predictive+Maintenance+Dataset',
 'https://archive.ics.uci.edu/ml/datasets/Wisesight+Sentiment+Corpus',
 'https://archive.ics.uci.edu/ml/datasets/Iris',
 'https://archive.ics.uci.edu/ml/datasets/Adult',
 'https://archive.ics.uci.edu/ml/datasets/Wine',
 'https://archive.ics.uci.edu/ml/datasets/Wine+Quality',
 'https://archive.ics.uci.edu/ml/datasets/Heart+Disease',
 'https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+%28Diagnostic%29',
 'https://archive.ics.uci.edu/ml/datasets/Bank+Marketing',
 'https://archive.ics.uci.edu/ml/datasets/Car+Evaluation',
 'https://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones',
 'https://archive.ics.uci.edu/ml/datasets/Abalone',
 'https://archive.ics.uci.edu/ml/datasets/Forest+Fires',
 'https://archive.ics.uci.edu/ml/datasets/Student+Performance']

In [107]:
dataset_names = []
dataset_datatypes = []
tasks = []
attribute_types = []
no_instances = []
no_attributes = []
year = []


#Looping through the each dataset urls-> 

for i in urls:
    driver.get(i)
    
    #dataset name
    
    try:
        dataset_name_obj = driver.find_element_by_xpath('//span[@class="heading"]/b')
        dataset_names.append(dataset_name_obj.text)
    except:
        dataset_names.append('-')
       
    #DATA SET DATA TYPES
    try:
        dataset_datatype_obj = driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/table[2]/tbody/tr[1]/td[2]/p')
        dataset_datatypes.append(dataset_datatype_obj.text)
    except:
        dataset_datatypes.append('-')
        
    #TASKS  
        
    try:
        dataset_task_obj = driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/table[2]/tbody/tr[3]/td[2]/p')
        tasks.append(dataset_task_obj.text)
    except:
        tasks.append('-')
      
    #ATTRIBUTE TYPES
        
    try:
        dataset_attr_type_obj = driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/table[2]/tbody/tr[2]/td[2]/p')
        attribute_types.append(dataset_attr_type_obj.text)
    except:
        attribute_types.append('-')
        
   
    #no of instances  
    try:
        dataset_instances_obj = driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/table[2]/tbody/tr[1]/td[4]/p')
        no_instances.append(dataset_instances_obj.text)
    except:
        no_instances.append('-')
        
     #no of attributes   
        
    try:
        dataset_attr_obj = driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/table[2]/tbody/tr[2]/td[4]/p')
        no_attributes.append(dataset_attr_obj.text)
    except:
        no_attributes.append('-')
    
      
    #year of DATASET
    try:
        year_obj = driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/table[2]/tbody/tr[2]/td[6]/p')
        year.append(year_obj.text)
    except:
        year.append('-')

In [108]:
#creating a dictionary of all the elements
dict = {
    'DATASET_NAME': dataset_names, 'DATASET_DATATYPE':dataset_datatypes,'DATA_TASK':tasks,
    'ATTRIBUTe_TYPES':attribute_types, 'NO_OF_INSTANCEs':no_instances,
    'NO_OF_ATTRIBUTES':no_instances,'YEAR_DATSET':year
}

#creating a Table from the dictionary
table = pd.DataFrame(dict)

In [109]:
table

,DATASET_NAME,DATASET_DATATYPE,DATA_TASK,ATTRIBUTe_TYPES,NO_OF_INSTANCEs,NO_OF_ATTRIBUTES,YEAR_DATSET
0,Communities and Crime Data Set,Multivariate,Regression,Real,1994,1994,2009-07-13
1,Synchronous Machine Data Set Data Set,Multivariate,Regression,Real,557,557,2021-04-21
2,Wikipedia Math Essentials Data Set,Time-Series,Regression,Real,731,731,2021-04-20
3,Wikipedia Math Essentials Data Set,Time-Series,Regression,Real,731,731,2021-04-20
4,Hungarian Chickenpox Cases Data Set,Time-Series,Regression,Real,521,521,2021-02-17
5,Myocardial infarction complications Data Set,Multivariate,Classification,Real,1700,1700,2020-12-09
6,Gait Classification Data Set,Multivariate,Classification,Real,48,48,2020-10-14
7,Codon usage Data Set,Multivariate,"Classification, Clustering",N/A,13028,13028,2020-10-03
8,in-vehicle coupon recommendation Data Set,Multivariate,Classification,N/A,12684,12684,2020-09-15
9,Dry Bean Dataset Data Set,Multivariate,Classification,"Integer, Real",13611,13611,2020-09-14
10,Intelligent Media Accelerometer and Gyroscope ...,Time-Series,Classification,Real,800,800,2020-09-03
11,AI4I 2020 Predictive Maintenance Dataset Data Set,"Multivariate, Time-Series","Classification, Regression, Causal-Discovery",Real,10000,10000,2020-08-30
12,Wisesight Sentiment Corpus Data Set,"Multivariate, Text",Classification,N/A,26737,26737,2020-08-25
13,Iris Data Set,Multivariate,Classification,Real,150,150,1988-07-01
14,Adult Data Set,Multivariate,Classification,"Categorical, Integer",48842,48842,1996-05-01
15,Wine Data Set,Multivariate,Classification,"Integer, Real",178,178,1991-07-01
16,Wine Quality Data Set,Multivariate,"Classification, Regression",Real,4898,4898,2009-10-07
17,Heart Disease Data Set,Multivariate,Classification,"Categorical, Integer, Real",303,303,1988-07-01
18,Breast Cancer Wisconsin (Diagnostic) Data Set,Multivariate,Classification,Real,569,569,1995-11-01
19,Bank Marketing Data Set,Multivariate,Classification,Real,45211,45211,2012-02-14
20,Car Evaluation Data Set,Multivariate,Classification,Categorical,1728,1728,1997-06-01
21,Human Activity Recognition Using Smartphones D...,"Multivariate, Time-Series","Classification, Clustering",N/A,10299,10299,2012-12-10
22,Abalone Data Set,Multivariate,Classification,"Categorical, Integer, Real",4177,4177,1995-12-01
23,Forest Fires Data Set,Multivariate,Regression,Real,517,517,2008-02-29
24,Student Performance Data Set,Multivariate,"Classification, Regression",Integer,649,649,2014-11-27